package org.project2.tz1_cinema.controller;

import org.project2.tz1_cinema.dto.*;
import org.project2.tz1_cinema.model.Actor;
import org.project2.tz1_cinema.model.Director;
import org.project2.tz1_cinema.model.Movie;
import org.project2.tz1_cinema.repo.ActorRepo;
import org.project2.tz1_cinema.service.ActorDirectorService;
import org.project2.tz1_cinema.service.ActorService;
import org.project2.tz1_cinema.service.DirectorService;
import org.project2.tz1_cinema.service.MovieService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;


@RestController
@RequestMapping("/admin")
public class AdminController {

    private final MovieService movieService;
    private final DirectorService directorService;
    private final ActorService actorService;
    private final ActorRepo actorRepo;
    private final ActorDirectorService actorDirectorService;

    @Autowired
    public AdminController(MovieService movieService, DirectorService directorService, ActorService actorService, ActorRepo actorRepo, ActorDirectorService actorDirectorService) {
        this.movieService = movieService;
        this.directorService = directorService;
        this.actorService = actorService;
        this.actorRepo = actorRepo;
        this.actorDirectorService = actorDirectorService;
    }

    @PostMapping(value = "/movies/add", consumes = "application/json")
    public ResponseEntity<Movie> addMovie(@RequestBody MovieDto movieDto) {
        System.out.println(":::::::::::::::::::::::::::::::::::::::::::");
        // Логика добавления фильма
        System.out.println(movieDto);
        System.out.println(":::::::::::::::::::::::::::::::::::::::::::");
        Movie movie1 = new Movie();
        movie1.setTitle(movieDto.getTitle());
        movie1.setCountry(movieDto.getCountry());
        movie1.setGenre(movieDto.getGenre());
        movie1.setActors(convertActor(movieDto.getActors()));
        List<Actor> actors = convertActor(movieDto.getActors());
        actorRepo.saveAll(actors);
        movie1.setComments(movie1.getComments());
        movie1.setDirector(convactorDtoDirector(movieDto.getDirector()));

        movieService.save(movie1);

        return ResponseEntity.status(HttpStatus.CREATED).body(movie1);
    }
/*
    {
        "title": "The Matrix",
            "country": "USA",
            "genre": "Sci-Fi",
            "releaseYear": 1999,
            "actors": [
        { "firstName": "Keanu", "lastName": "Reeves", "yearOfBirth": 1964 },
        { "firstName": "Laurence", "lastName": "Fishburne", "yearOfBirth": 1961 },
        { "firstName": "Carrie-Anne", "lastName": "Moss", "yearOfBirth": 1967 }
  ],
        "director": {
        "firstName": "Lana",
                "lastName": "Wachowski",
                "yearOfBirth": 1965
    }
    }
*/


    @PostMapping("/actor/add")
    public ResponseEntity<ActorAddDto> addActor(@RequestBody ActorAddDto actorDto) {
        // Validate ActorDto (firstName and lastName must be provided)
        if (actorDto.getFirstName() == null || actorDto.getFirstName().isEmpty() || actorDto.getLastName() == null || actorDto.getLastName().isEmpty()) {
            return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
        }

        // Add Actor through the service
        actorService.save(convactorDto(actorDto));

        // Return the saved ActorDto (without id, because it's auto-generated by the database)
        return new ResponseEntity<>(actorDto, HttpStatus.CREATED);
    }




    @PostMapping("/director/add")
    public ResponseEntity<DirectorDto> addDirector(@RequestBody DirectorDto directorDto) {
        // Validate DirectorDto
        System.out.println("1111111111111111111111111111111");
        // Add Director through the service
        actorDirectorService.addDirector(directorDto);
        System.out.println("2222222222222222222222222222222222");

        // Return the saved DirectorDto
        return new ResponseEntity<>(directorDto, HttpStatus.CREATED);
    }
    //{
    //  "firstName": "Martin",
    //  "lastName": "Scorsese",
    //  "yearOfBirth": "1942"
    //}

    private Actor convactorDto(ActorAddDto actorAddDto) {
        Actor actor = new Actor();
        actor.setFirstName(actorAddDto.getFirstName());
        actor.setLastName(actorAddDto.getLastName());
        actor.setYearOfBirth(actorAddDto.getYearOfBirth());
        return actor;
    }

    private Director convactorDtoDirector(DirectorAddDto DirectorAddDto) {
        Director director = new Director();
        director.setFirstName(DirectorAddDto.getFirstName());
        director.setLastName(DirectorAddDto.getLastName());
        director.setYearOfBirth(DirectorAddDto.getYearOfBirth());
        System.out.println(
                ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
        );System.out.println(director);
        System.out.println(DirectorAddDto);
        return director;
    }

    private List<Actor> convertActor (List<ActorAddDto> actorAddDtoList) {
        List<Actor> actors = new ArrayList<>();
        for (ActorAddDto actorAddDto : actorAddDtoList) {
            Actor actor = convactorDto(actorAddDto);
            actor.setFirstName(actorAddDto.getFirstName());
            actor.setLastName(actorAddDto.getLastName());
            actor.setYearOfBirth(actorAddDto.getYearOfBirth());
            actors.add(actor);
        }
        return actors;
    }
}
