version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cinema_db
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinema_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cinema
      SPRING_DATASOURCE_USERNAME: cinema_user
      SPRING_DATASOURCE_PASSWORD: cinema_pass

volumes:
  db_data:
